spring:
  application:
    name: healthAnalysis-service
  config:
    import: nacos:healthAnalysis-service-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml