spring:
  application:
    name: usermanagement-service
  config:
    import: nacos:usermanagement-service-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/usermanagement_db?useSSL=false
    username: root
    password: MyNewPass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    cn.itcast: debug
  pattern:
    datefotmat: MM-dd HH:mm:ss:$$$

aliyun:
  sms:
    access-key-id: "LTAI5tHyMH27LsCN4HE9vexN"
    access-key-secret: "zM8wTRxetOOvcwPp3V4cQVu1Sxmiqm"
    sign-name: "阿里云短信测试"
    template-code: "SMS_154950909"
